language: r
sudo: required

env: NOT_CRAN="true"

r_binary_packages:
  - testthat
  - knitr

branches:
  only:
    - master
    - release
    - dev
    
notifications:
  email:
    on_success: change
    on_failure: change
    