variables:
- group: GH
- name: R_LIBS_USER
  value: '$(Agent.BuildDirectory)/R/library'

pool:
  vmImage: 'ubuntu-latest'

container: $[variables['rockerImage']]

steps:
- bash: |
    echo "options(repos = '$(cranRepo)')" > ~/.Rprofile
    echo ".libPaths(c('$R_LIBS_USER', .libPaths()))" >> ~/.Rprofile
    mkdir -p $R_LIBS_USER
  displayName: 'Setup R library directory'

- task: CacheBeta@0
  inputs:
    key: ./DESCRIPTION | "$(rockerImage)" | "$(cranRepo)"
    path: $(R_LIBS_USER)
  displayName: 'Caching packages'

- bash: |
    Rscript -e "pkgs <- c('remotes', 'rcmdcheck'); if(length(find.package(pkgs, quiet=TRUE)) != length(pkgs)) install.packages(pkgs)"
    Rscript -e "remotes::install_deps(dependencies=TRUE)"
  displayName: 'Installing package dependencies'

- bash: |
    Rscript -e "f <- pkgbuild::build(dest_path='$(Build.ArtifactStagingDirectory)'); rcmdcheck::rcmdcheck(f, args='--no-manual', error_on='warning', check_dir='check')"
  displayName: 'Checking package'
